package com.jm.reader.ui.strings

/**
 * All user-facing UI strings, localised into 简体中文 / 繁體中文 / English.
 * Screens read the current table via [LocalAppStrings].
 */
data class AppStrings(
    // App & navigation
    val appName: String,
    val home: String,
    val categories: String,
    val library: String,
    val member: String,
    val search: String,
    val searchComicHint: String,
    val latest: String,
    val refresh: String,
    val forYou: String,
    val novels: String,
    val movies: String,
    val games: String,
    val blogs: String,
    val forum: String,
    val quickWeek: String,
    val quickDaily: String,
    val quickHot: String,
    val quickNovels: String,
    val quickMovies: String,
    val quickGames: String,
    val quickBlogs: String,
    val quickCategories: String,
    // Comic detail
    val comicDetail: String,
    val startReading: String,
    val favorite: String,
    val favorited: String,
    val loginFirst: String,
    val addedFavorite: String,
    val removedFavorite: String,
    val paidContentNotice: String,
    val paidContentLocked: String,
    val authorLabel: String,
    val tagLabel: String,
    val views: String,
    val pages: String,
    val likes: String,
    val chapters: String,
    val singleFileWork: String,
    val relatedWorks: String,
    val noDescription: String,
    val loadFail: String,
    // Reader
    val back: String,
    val toggleMode: String,
    val chapterList: String,
    val chooseChapter: String,
    val singleFile: String,
    val current: String,
    val close: String,
    val prevChapter: String,
    val nextChapter: String,
    val imageLoadFail: String,
    val retry: String,
    val chapterFmt: String,          // "第 %1\$d 話" / "Episode %1\$d"
    // Search
    val clear: String,
    val hotTagsTitle: String,
    val noResult: String,
    val searchWork: String,
    val searchAuthor: String,
    val searchById: String,
    val searchAuthorHint: String,
    val searchIdHint: String,
    val searchIdOpen: String,
    val searchTotalFmt: String,      // "共 %1\$d 部作品"
    val searchIdNotFound: String,
    val searchIdInvalid: String,
    val searchLooksLikeId: String,
    val noMore: String,
    // Library
    val favorites: String,
    val history: String,
    val downloads: String,
    val libraryLoginRequired: String,
    val goLogin: String,
    val emptyFavorites: String,
    val emptyHistory: String,
    val emptyDownloads: String,
    val historyClear: String,
    val historyClearConfirm: String,
    val historyCountFmt: String,     // "共 %1\$d 条记录"
    // Member & auth
    val notLoggedIn: String,
    val login: String,
    val register: String,
    val logout: String,
    val memberProfile: String,
    val adFreeMember: String,
    val uidLabel: String,
    val levelLabel: String,
    val coinLabel: String,
    val checkIn: String,
    val notifications: String,
    val username: String,
    val password: String,
    val email: String,
    val confirmPassword: String,
    val gender: String,
    val male: String,
    val female: String,
    val other: String,
    val fillComplete: String,
    val passwordMismatch: String,
    val registerSuccess: String,
    val enterAccountPassword: String,
    val loginFailed: String,
    val passwordTooShort: String,
    val invalidEmail: String,
    val language: String,
    val simplifiedChinese: String,
    val traditionalChinese: String,
    val english: String,
    // Daily check-in
    val signedDaysFmt: String,       // "已簽到 %1\$d 天"
    val todayNoWork: String,
    val signIn: String,
    // Week
    val weekRanking: String,
    // Generic
    val list: String,
    val loading: String,
    val noData: String,
    val empty: String,
    // Novels
    val searchNovelHint: String,
    val emptyNovels: String,
    val novelDetail: String,
    val noChapters: String,
    val needPurchase: String,
    val read: String,
    // Movies
    val emptyMovies: String,
    val movieDetail: String,
    val openInBrowser: String,
    val videoAddress: String,
    // Games / Blogs / Forum
    val emptyGames: String,
    val emptyBlogs: String,
    val article: String,
    val emptyForum: String,
    // Download
    val download: String,
    val downloaded: String,
    val downloading: String,
    val downloadComplete: String,
    val downloadFailed: String,
    val offlineRead: String,
    val delete: String,
    val deleteConfirmFmt: String,    // "確定刪除已下載的《%1\$s》？"
    val downloadProgressFmt: String, // "下載中 %1\$d / %2\$d"
    val downloadAlready: String,
    val downloadStart: String,
    val myDownloads: String,
    // Splash
    val bootFail: String,
    // Crash report
    val crashTitle: String,
    val crashHint: String,
    val copyLog: String,
    // Common
    val cancel: String,
    val confirm: String,
    val refreshPage: String,
    // API errors - a bare numeric code is never shown to the reader
    val errNetwork: String,
    val errTimeout: String,
    val errServer: String,
    val errNotFound: String,
    val errForbidden: String,
    val errUnauthorized: String,
    val errRateLimited: String,
    val errNoHost: String,
    val errRequestFailedFmt: String, // "請求失敗 (%1\$d)"
    // Adaptive search
    val searchAdaptiveHint: String,
    val searchJumpIdFmt: String,     // "開啟 JM%1\$s"
    // Daily check-in
    val alreadySignedToday: String,
    val signInSuccessMsg: String,
    val signInFailedMsg: String,
    val dailyProgressFmt: String,    // "連續簽到進度 %1\$s"
    // Registration
    val registerNeedConfirm: String,
    val registerFailed: String,
    // Library / local history
    val libraryHistoryHint: String,
    val historyResumeFmt: String,    // "上次讀到 %1\$s"
    // Member
    val sessionExpired: String,
) {
    companion object {
        fun forLanguage(lang: UiLanguage): AppStrings = when (lang) {
            UiLanguage.ZH_CN -> ZhCN
            UiLanguage.ZH_TW -> ZhTW
            UiLanguage.EN -> En
        }
    }
}

/** 简体中文 */
val ZhCN = AppStrings(
    appName = "JM Reader",
    home = "首页",
    categories = "分类",
    library = "书库",
    member = "我的",
    search = "搜索",
    searchComicHint = "搜索漫画 / 作者 / ID",
    latest = "最新",
    refresh = "刷新",
    forYou = "为你推荐",
    novels = "小说",
    movies = "影片",
    games = "游戏",
    blogs = "博客",
    forum = "论坛",
    quickWeek = "每周",
    quickDaily = "每日",
    quickHot = "热门",
    quickNovels = "小说",
    quickMovies = "影片",
    quickGames = "游戏",
    quickBlogs = "博客",
    quickCategories = "分类",
    comicDetail = "作品详情",
    startReading = "开始阅读",
    favorite = "收藏",
    favorited = "已收藏",
    loginFirst = "请先登录",
    addedFavorite = "已加入收藏",
    removedFavorite = "已取消收藏",
    paidContentNotice = "此作品为付费内容，请使用官方 App 购买后再阅读",
    paidContentLocked = "此作品需要购买才能阅读。",
    authorLabel = "作者：",
    tagLabel = "标签：",
    views = "浏览",
    pages = "页数",
    likes = "赞",
    chapters = "章节",
    singleFileWork = "单文件作品，点击阅读",
    relatedWorks = "相关作品",
    noDescription = "（无描述）",
    loadFail = "加载失败",
    back = "返回",
    toggleMode = "切换模式",
    chapterList = "章节",
    chooseChapter = "选择章节",
    singleFile = "单文件",
    current = "当前",
    close = "关闭",
    prevChapter = "上一话",
    nextChapter = "下一话",
    imageLoadFail = "图片加载失败",
    retry = "重试",
    chapterFmt = "第 %1\$d 话",
    clear = "清除",
    hotTagsTitle = "热门标签",
    noResult = "无搜索结果",
    searchWork = "作品",
    searchAuthor = "作者",
    searchById = "ID",
    searchAuthorHint = "输入作者名",
    searchIdHint = "输入作品 ID",
    searchIdOpen = "打开",
    searchTotalFmt = "共 %1\$d 部作品",
    searchIdNotFound = "未找到该 ID 的作品",
    searchIdInvalid = "请输入数字作品 ID",
    searchLooksLikeId = "看起来是作品 ID，可直接打开",
    noMore = "没有更多了",
    favorites = "收藏",
    history = "历史",
    downloads = "下载",
    libraryLoginRequired = "登录后才能使用书库功能",
    goLogin = "前往登录",
    emptyFavorites = "暂无收藏",
    emptyHistory = "暂无观看历史",
    emptyDownloads = "暂无下载",
    historyClear = "清空历史",
    historyClearConfirm = "确定清空全部浏览记录？",
    historyCountFmt = "共 %1\$d 条记录",
    notLoggedIn = "尚未登录",
    login = "登录",
    register = "注册",
    logout = "退出登录",
    memberProfile = "会员",
    adFreeMember = "去广告会员",
    uidLabel = "UID",
    levelLabel = "等级",
    coinLabel = "硬币",
    checkIn = "每日签到",
    notifications = "通知",
    username = "账号",
    password = "密码",
    email = "Email",
    confirmPassword = "确认密码",
    gender = "性别",
    male = "男",
    female = "女",
    other = "其他",
    fillComplete = "请填写完整资料",
    passwordMismatch = "两次密码不一致",
    registerSuccess = "注册成功！请返回登录页登录",
    enterAccountPassword = "请输入账号与密码",
    loginFailed = "账号或密码错误",
    passwordTooShort = "密码至少 8 位",
    invalidEmail = "邮箱格式不正确",
    language = "语言",
    simplifiedChinese = "简体中文",
    traditionalChinese = "繁體中文",
    english = "English",
    signedDaysFmt = "已签到 %1\$d 天",
    todayNoWork = "今日暂无作品",
    signIn = "签到",
    weekRanking = "每周必看",
    list = "列表",
    loading = "加载中",
    noData = "暂无数据",
    empty = "暂无内容",
    searchNovelHint = "搜索小说",
    emptyNovels = "暂无小说",
    novelDetail = "小说详情",
    noChapters = "暂无章节",
    needPurchase = "需购买",
    read = "阅读",
    emptyMovies = "暂无影片",
    movieDetail = "影片详情",
    openInBrowser = "在浏览器中观看",
    videoAddress = "影片地址",
    emptyGames = "暂无游戏",
    emptyBlogs = "暂无文章",
    article = "文章",
    emptyForum = "暂无讨论",
    download = "下载",
    downloaded = "已下载",
    downloading = "下载中",
    downloadComplete = "下载完成",
    downloadFailed = "下载失败",
    offlineRead = "离线阅读",
    delete = "删除",
    deleteConfirmFmt = "确定删除已下载的《%1\$s》？",
    downloadProgressFmt = "下载中 %1\$d / %2\$d",
    downloadAlready = "已下载，点击离线阅读",
    downloadStart = "开始下载",
    myDownloads = "我的下载",
    bootFail = "启动失败",
    crashTitle = "上次应用崩溃",
    crashHint = "已记录上次崩溃的日志，点击「复制日志」可复制报错信息反馈给开发者。",
    copyLog = "复制日志",
    cancel = "取消",
    confirm = "确定",
    refreshPage = "重试",
    errNetwork = "网络连接失败，请检查网络或代理",
    errTimeout = "连接超时，请稍后重试",
    errServer = "服务器繁忙，请稍后重试",
    errNotFound = "内容不存在或已下架",
    errForbidden = "当前网络被限制访问，请切换线路或代理",
    errUnauthorized = "登录已过期，请重新登录",
    errRateLimited = "请求过于频繁，请稍后再试",
    errNoHost = "无法连接服务器，请检查网络后重试",
    errRequestFailedFmt = "请求失败 (%1\$d)",
    searchAdaptiveHint = "搜索漫画 / 作者 / JM号",
    searchJumpIdFmt = "打开 JM%1\$s",
    alreadySignedToday = "今日已签到",
    signInSuccessMsg = "签到成功",
    signInFailedMsg = "签到失败，请稍后重试",
    dailyProgressFmt = "连续签到进度 %1\$s",
    registerNeedConfirm = "注册成功！请到邮箱确认后再登录",
    registerFailed = "注册失败，请检查填写的信息",
    libraryHistoryHint = "本地历史无需登录，离线也能查看",
    historyResumeFmt = "上次读到 %1\$s",
    sessionExpired = "登录已过期，请重新登录",
)

/** 繁體中文 */
val ZhTW = AppStrings(
    appName = "JM Reader",
    home = "首頁",
    categories = "分類",
    library = "書庫",
    member = "我的",
    search = "搜尋",
    searchComicHint = "搜尋漫畫 / 作者 / ID",
    latest = "最新",
    refresh = "刷新",
    forYou = "為你推薦",
    novels = "小說",
    movies = "影片",
    games = "遊戲",
    blogs = "部落格",
    forum = "論壇",
    quickWeek = "週末",
    quickDaily = "每日",
    quickHot = "熱門",
    quickNovels = "小說",
    quickMovies = "影片",
    quickGames = "遊戲",
    quickBlogs = "部落格",
    quickCategories = "分類",
    comicDetail = "作品詳情",
    startReading = "開始閱讀",
    favorite = "收藏",
    favorited = "已收藏",
    loginFirst = "請先登入",
    addedFavorite = "已加入收藏",
    removedFavorite = "已取消收藏",
    paidContentNotice = "此作品為付費內容，請使用官方 App 購買後再閱讀",
    paidContentLocked = "此作品需要購買才能閱讀。",
    authorLabel = "作者：",
    tagLabel = "標籤：",
    views = "瀏覽",
    pages = "頁數",
    likes = "讚",
    chapters = "章節",
    singleFileWork = "單一檔案作品，點擊閱讀",
    relatedWorks = "相關作品",
    noDescription = "（無描述）",
    loadFail = "載入失敗",
    back = "返回",
    toggleMode = "切換模式",
    chapterList = "章節",
    chooseChapter = "選擇章節",
    singleFile = "單一檔案",
    current = "當前",
    close = "關閉",
    prevChapter = "上一話",
    nextChapter = "下一話",
    imageLoadFail = "圖片載入失敗",
    retry = "重試",
    chapterFmt = "第 %1\$d 話",
    clear = "清除",
    hotTagsTitle = "熱門標籤",
    noResult = "無搜尋結果",
    searchWork = "作品",
    searchAuthor = "作者",
    searchById = "ID",
    searchAuthorHint = "輸入作者名",
    searchIdHint = "輸入作品 ID",
    searchIdOpen = "開啟",
    searchTotalFmt = "共 %1\$d 部作品",
    searchIdNotFound = "找不到該 ID 的作品",
    searchIdInvalid = "請輸入數字作品 ID",
    searchLooksLikeId = "看起來是作品 ID，可直接開啟",
    noMore = "沒有更多了",
    favorites = "收藏",
    history = "歷史",
    downloads = "下載",
    libraryLoginRequired = "登入後才能使用書庫功能",
    goLogin = "前往登入",
    emptyFavorites = "暫無收藏",
    emptyHistory = "暫無觀看歷史",
    emptyDownloads = "暫無下載",
    historyClear = "清空歷史",
    historyClearConfirm = "確定清空全部瀏覽記錄？",
    historyCountFmt = "共 %1\$d 筆記錄",
    notLoggedIn = "尚未登入",
    login = "登入",
    register = "註冊",
    logout = "登出",
    memberProfile = "會員",
    adFreeMember = "去廣告會員",
    uidLabel = "UID",
    levelLabel = "等級",
    coinLabel = "硬幣",
    checkIn = "每日簽到",
    notifications = "通知",
    username = "帳號",
    password = "密碼",
    email = "Email",
    confirmPassword = "確認密碼",
    gender = "性別",
    male = "男",
    female = "女",
    other = "其他",
    fillComplete = "請填寫完整資料",
    passwordMismatch = "兩次密碼不一致",
    registerSuccess = "註冊成功！請回登入頁登入",
    enterAccountPassword = "請輸入帳號與密碼",
    loginFailed = "帳號或密碼錯誤",
    passwordTooShort = "密碼至少 8 位",
    invalidEmail = "電子郵件格式不正確",
    language = "語言",
    simplifiedChinese = "简体中文",
    traditionalChinese = "繁體中文",
    english = "English",
    signedDaysFmt = "已簽到 %1\$d 天",
    todayNoWork = "今日暫無作品",
    signIn = "簽到",
    weekRanking = "每週必看",
    list = "列表",
    loading = "載入中",
    noData = "暫無資料",
    empty = "暫無內容",
    searchNovelHint = "搜尋小說",
    emptyNovels = "暫無小說",
    novelDetail = "小說詳情",
    noChapters = "暫無章節",
    needPurchase = "需購買",
    read = "閱讀",
    emptyMovies = "暫無影片",
    movieDetail = "影片詳情",
    openInBrowser = "在瀏覽器中觀看",
    videoAddress = "影片位址",
    emptyGames = "暫無遊戲",
    emptyBlogs = "暫無文章",
    article = "文章",
    emptyForum = "暫無討論",
    download = "下載",
    downloaded = "已下載",
    downloading = "下載中",
    downloadComplete = "下載完成",
    downloadFailed = "下載失敗",
    offlineRead = "離線閱讀",
    delete = "刪除",
    deleteConfirmFmt = "確定刪除已下載的《%1\$s》？",
    downloadProgressFmt = "下載中 %1\$d / %2\$d",
    downloadAlready = "已下載，點擊離線閱讀",
    downloadStart = "開始下載",
    myDownloads = "我的下載",
    bootFail = "啟動失敗",
    crashTitle = "上次應用當機",
    crashHint = "已記錄上次當機的日誌，點擊「複製日誌」可複製報錯資訊回報給開發者。",
    copyLog = "複製日誌",
    cancel = "取消",
    confirm = "確定",
    refreshPage = "重試",
    errNetwork = "網路連線失敗，請檢查網路或代理",
    errTimeout = "連線逾時，請稍後重試",
    errServer = "伺服器繁忙，請稍後重試",
    errNotFound = "內容不存在或已下架",
    errForbidden = "目前網路被限制存取，請切換線路或代理",
    errUnauthorized = "登入已過期，請重新登入",
    errRateLimited = "請求過於頻繁，請稍後再試",
    errNoHost = "無法連線伺服器，請檢查網路後重試",
    errRequestFailedFmt = "請求失敗 (%1\$d)",
    searchAdaptiveHint = "搜尋漫畫 / 作者 / JM號",
    searchJumpIdFmt = "開啟 JM%1\$s",
    alreadySignedToday = "今日已簽到",
    signInSuccessMsg = "簽到成功",
    signInFailedMsg = "簽到失敗，請稍後重試",
    dailyProgressFmt = "連續簽到進度 %1\$s",
    registerNeedConfirm = "註冊成功！請到信箱確認後再登入",
    registerFailed = "註冊失敗，請檢查填寫的資訊",
    libraryHistoryHint = "本地歷史無需登入，離線也能查看",
    historyResumeFmt = "上次讀到 %1\$s",
    sessionExpired = "登入已過期，請重新登入",
)

/** English */
val En = AppStrings(
    appName = "JM Reader",
    home = "Home",
    categories = "Categories",
    library = "Library",
    member = "Me",
    search = "Search",
    searchComicHint = "Search comics / authors / ID",
    latest = "Latest",
    refresh = "Refresh",
    forYou = "For you",
    novels = "Novels",
    movies = "Movies",
    games = "Games",
    blogs = "Blogs",
    forum = "Forum",
    quickWeek = "Weekly",
    quickDaily = "Daily",
    quickHot = "Hot",
    quickNovels = "Novels",
    quickMovies = "Movies",
    quickGames = "Games",
    quickBlogs = "Blogs",
    quickCategories = "Categories",
    comicDetail = "Comic details",
    startReading = "Start reading",
    favorite = "Favorite",
    favorited = "Favorited",
    loginFirst = "Please log in first",
    addedFavorite = "Added to favorites",
    removedFavorite = "Removed from favorites",
    paidContentNotice = "This is paid content. Please purchase it in the official app first",
    paidContentLocked = "This work must be purchased to read.",
    authorLabel = "Author: ",
    tagLabel = "Tags: ",
    views = "Views",
    pages = "Pages",
    likes = "Likes",
    chapters = "Chapters",
    singleFileWork = "Single-file work, tap to read",
    relatedWorks = "Related",
    noDescription = "(No description)",
    loadFail = "Failed to load",
    back = "Back",
    toggleMode = "Toggle mode",
    chapterList = "Chapters",
    chooseChapter = "Choose chapter",
    singleFile = "Single file",
    current = "Current",
    close = "Close",
    prevChapter = "Previous",
    nextChapter = "Next",
    imageLoadFail = "Failed to load image",
    retry = "Retry",
    chapterFmt = "Episode %1\$d",
    clear = "Clear",
    hotTagsTitle = "Hot tags",
    noResult = "No results",
    searchWork = "Works",
    searchAuthor = "Author",
    searchById = "ID",
    searchAuthorHint = "Enter an author name",
    searchIdHint = "Enter a comic ID",
    searchIdOpen = "Open",
    searchTotalFmt = "%1\$d works",
    searchIdNotFound = "No comic found for this ID",
    searchIdInvalid = "Enter a numeric comic ID",
    searchLooksLikeId = "Looks like a comic ID",
    noMore = "No more results",
    favorites = "Favorites",
    history = "History",
    downloads = "Downloads",
    libraryLoginRequired = "Log in to use the library",
    goLogin = "Go to login",
    emptyFavorites = "No favorites yet",
    emptyHistory = "No history yet",
    emptyDownloads = "No downloads yet",
    historyClear = "Clear history",
    historyClearConfirm = "Clear all browsing history?",
    historyCountFmt = "%1\$d records",
    notLoggedIn = "Not logged in",
    login = "Log in",
    register = "Sign up",
    logout = "Log out",
    memberProfile = "Member",
    adFreeMember = "Ad-free member",
    uidLabel = "UID",
    levelLabel = "Level",
    coinLabel = "Coins",
    checkIn = "Daily check-in",
    notifications = "Notifications",
    username = "Username",
    password = "Password",
    email = "Email",
    confirmPassword = "Confirm password",
    gender = "Gender",
    male = "Male",
    female = "Female",
    other = "Other",
    fillComplete = "Please fill in all fields",
    passwordMismatch = "Passwords do not match",
    registerSuccess = "Registered! Please log in",
    enterAccountPassword = "Enter username and password",
    loginFailed = "Wrong username or password",
    passwordTooShort = "Password must be at least 8 characters",
    invalidEmail = "Invalid email address",
    language = "Language",
    simplifiedChinese = "简体中文",
    traditionalChinese = "繁體中文",
    english = "English",
    signedDaysFmt = "Signed in %1\$d days",
    todayNoWork = "Nothing today",
    signIn = "Check in",
    weekRanking = "Weekly picks",
    list = "List",
    loading = "Loading",
    noData = "No data",
    empty = "Nothing here",
    searchNovelHint = "Search novels",
    emptyNovels = "No novels",
    novelDetail = "Novel details",
    noChapters = "No chapters",
    needPurchase = "Paid",
    read = "Read",
    emptyMovies = "No videos",
    movieDetail = "Video details",
    openInBrowser = "Watch in browser",
    videoAddress = "Video URL",
    emptyGames = "No games",
    emptyBlogs = "No posts",
    article = "Post",
    emptyForum = "No discussions",
    download = "Download",
    downloaded = "Downloaded",
    downloading = "Downloading",
    downloadComplete = "Download complete",
    downloadFailed = "Download failed",
    offlineRead = "Read offline",
    delete = "Delete",
    deleteConfirmFmt = "Delete downloaded \"%1\$s\"?",
    downloadProgressFmt = "Downloading %1\$d / %2\$d",
    downloadAlready = "Downloaded, tap to read offline",
    downloadStart = "Start download",
    myDownloads = "My downloads",
    bootFail = "Startup failed",
    crashTitle = "The app crashed last time",
    crashHint = "A crash log was saved. Tap \"Copy log\" to copy the error details for reporting.",
    copyLog = "Copy log",
    cancel = "Cancel",
    confirm = "OK",
    refreshPage = "Retry",
    errNetwork = "Network unavailable. Check your connection or proxy.",
    errTimeout = "Connection timed out. Try again later.",
    errServer = "Server busy. Try again later.",
    errNotFound = "Not found or removed",
    errForbidden = "Access blocked on this network. Switch route or proxy.",
    errUnauthorized = "Session expired, please log in again",
    errRateLimited = "Too many requests. Try again later.",
    errNoHost = "Cannot reach the server. Check your connection.",
    errRequestFailedFmt = "Request failed (%1\$d)",
    searchAdaptiveHint = "Search comics / authors / JM id",
    searchJumpIdFmt = "Open JM%1\$s",
    alreadySignedToday = "Checked in today",
    signInSuccessMsg = "Check-in complete",
    signInFailedMsg = "Check-in failed, try again later",
    dailyProgressFmt = "Streak progress %1\$s",
    registerNeedConfirm = "Registered! Confirm your email before logging in",
    registerFailed = "Registration failed. Check the information you entered.",
    libraryHistoryHint = "Local history needs no account and works offline",
    historyResumeFmt = "Last read %1\$s",
    sessionExpired = "Session expired, please log in again",
)
